### ISSUE TITLE
Any scientific paper that used this framework?

### ISSUE THREAD

**Issue by rmlz** [mmmatthew/swmm_calibration#2]
Hi! My name is Ramon Barros and I've been using spotpy to calibrate CE-QUAL-W2 lake model.

I'd like to know if there's any scientific work in which you report your experience using spotpy and swmm model.

Thanks very much in advance.

**Comment by mmmatthew** [comment]
Hi Ramon,
I am indeed finishing a publication right now, but it focuses on the data
used for calibration rather than SPOTPY as a tool. I can provide more
specific information depending on what you are looking for.

**Comment by rmlz** [comment]
Matthew, that's awesome.

Actually, i'm interested in the general experience of using spotpy and handling data.
Look, I'm a biologist and math modelling is a very new issue that came into my studies (I've been studying it for 1 year), hence, the mathematical language can be sort of difficult for me sometimes (I'm improving!). 

I've been looking around for articles in which the main subject is mathematical modelling of environments, and I've seen this repo while googling for "spotpy". I'd like to see your paper once you have it published, as I'm looking for any insights I can take from calibration works.

May I ask you if you did any sensitivity analysis on swmm parameters?

Have a good one.

**Comment by mmmatthew** [comment]
Hi Ramon, please contact me at matthew.moydevitry@eawag.ch and we can keep
in touch.

**Comment by mmmatthew** [comment]
This thread continues by email. Closing issue now.
